version: '3'
services:
  api:
    build: .
    environment:
      - AWS_PROFILE=discutext
      - AWS_S3_STORAGE_BUCKET=discutext-development-us-east-1-andrew
    ports:
      - "5050:5000"
    volumes:
      - .:/usr/src
