version: '3'
services:
  api:
    build: .
    environment:
      - AWS_PROFILE=discutext
      - AWS_S3_STORAGE_BUCKET=development-discutext-us-east-2
    ports:
      - "5050:5000"
    volumes:
      - .:/usr/src
      - ~/.aws:/root/.aws
