#!/usr/bin/env bash

set -x

if [ ! -d ".venv" ]; then
    echo "Creating new python3 virtualenv in .venv..."
    python3.9 -m venv .venv
fi

# shellcheck disable=SC1091
source .venv/bin/activate

./scripts/update
