#!/usr/bin/env bash

set -e

if ! command -v mise &> /dev/null; then
    echo "mise tool manager not installed. See https://mise.jdx.dev/getting-started.html to continue."
    exit 1
fi

if ! command -v uv &> /dev/null; then
    echo "uv package manager not installed. See https://docs.astral.sh/uv/getting-started/installation/ to continue."
    exit 1
fi

./scripts/update
